APIConf:
  Host: "0.0.0.0"
  Port: 8080

Node: https://evm-rpc-http-andromeda.galactica.com

RegistryAddress: 0x29eFd381054edDb68163C0D34546d9EaE9710091

MerkleProofService:
  URL: grpc-merkle-41238.galactica.com:443
  TLS: true
